export const MISSIONS = [
  {
    id: 0,
    title: '밀기 미션',
    introTitle: '첫 번째 미션!',
    introDesc: '삼각형을 오른쪽으로 4칸, 위로 2칸 밀어봐. 밀기는 도형을 원하는 방향으로 이동시키는 거야!',
    motivationText: '도형의 모양은 그대로! 위치만 바뀌는 거야. 할 수 있어!',
    successTitle: '완벽해!',
    successDesc: '밀기 완료! 도형이 새 자리에 딱 맞게 이동했어.',
    desc: '삼각형을 오른쪽 4칸, 위 2칸 밀어보세요!',
    start:  [{ x: -4, y: -2 }, { x: -2, y: -2 }, { x: -3, y: 0 }],
    target: [{ x:  0, y:  0 }, { x:  2, y:  0 }, { x:  1, y: 2 }],
    allowedOps: ['translate', 'flip', 'rotate'],
  },
  {
    id: 1,
    title: '뒤집기 미션',
    introTitle: '두 번째 미션!',
    introDesc: '사각형을 좌우로 뒤집어봐. 거울에 비친 것처럼 반대쪽에 나타나게 해봐!',
    motivationText: '뒤집기 후에 모양은 같지만 방향이 반대가 돼. 마치 거울 속의 나처럼!',
    successTitle: '굉장해!',
    successDesc: '뒤집기 성공! 거울 속 사각형이 완성됐어.',
    desc: '사각형을 좌우로 뒤집어보세요!',
    start:  [{ x: 1, y: 0 }, { x: 3, y: 0 }, { x: 3, y: 2 }, { x: 1, y: 2 }],
    target: [{ x:-1, y: 0 }, { x:-3, y: 0 }, { x:-3, y: 2 }, { x:-1, y: 2 }],
    allowedOps: ['translate', 'flip', 'rotate'],
  },
  {
    id: 2,
    title: '돌리기 미션',
    introTitle: '세 번째 미션!',
    introDesc: '삼각형을 반시계 방향으로 90도 돌려봐. 도형을 빙글빙글 돌리는 거야!',
    motivationText: '돌리기는 도형의 방향을 바꾸는 거야. 팽이처럼 빙글빙글!',
    successTitle: '최고야!',
    successDesc: '돌리기 성공! 삼각형이 90도 회전했어.',
    desc: '삼각형을 반시계 방향으로 90도 돌려보세요!',
    start:  [{ x: 1, y: 0 }, { x: 3, y: 0 }, { x: 2, y: 2 }],
    target: [{ x: 0, y: 1 }, { x: 0, y: 3 }, { x:-2, y: 2 }],
    allowedOps: ['translate', 'flip', 'rotate'],
  },
  {
    id: 3,
    title: '도전 미션',
    introTitle: '도전 미션!',
    introDesc: '오각형을 오른쪽으로 3칸 밀고 위아래로 뒤집어봐. 두 가지 이동을 동시에!',
    motivationText: '두 가지 이동을 한번에 할 수 있어. 순서대로 차근차근!',
    successTitle: '천재!',
    successDesc: '두 가지 이동을 모두 성공했어! 대단해!',
    desc: '오각형을 오른쪽 3칸, 위아래로 뒤집어보세요!',
    start:  [{ x:-2, y: 0 }, { x:-1, y: 2 }, { x: 0, y: 3 }, { x: 1, y: 2 }, { x: 2, y: 0 }],
    target: [{ x: 1, y: 0 }, { x: 2, y:-2 }, { x: 3, y:-3 }, { x: 4, y:-2 }, { x: 5, y: 0 }],
    allowedOps: ['translate', 'flip', 'rotate'],
  },
];
